// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wrapper.proto

#include "Wrapper.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace xpilot {
constexpr Wrapper::Wrapper(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : timestamp_(nullptr)
  , _oneof_case_{}{}
struct WrapperDefaultTypeInternal {
  constexpr WrapperDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~WrapperDefaultTypeInternal() {}
  union {
    Wrapper _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT WrapperDefaultTypeInternal _Wrapper_default_instance_;
}  // namespace xpilot
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Wrapper_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Wrapper_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Wrapper_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Wrapper_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xpilot::Wrapper, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::xpilot::Wrapper, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::xpilot::Wrapper, timestamp_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::xpilot::Wrapper, msg_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::xpilot::Wrapper)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::xpilot::_Wrapper_default_instance_),
};

const char descriptor_table_protodef_Wrapper_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rWrapper.proto\022\006xpilot\032\037google/protobuf"
  "/timestamp.proto\032\024XplaneDatarefs.proto\032\020"
  "PluginHash.proto\032\023PluginVersion.proto\032\021C"
  "SLValidate.proto\032\016AddPlane.proto\032\021Change"
  "Model.proto\032\024PositionUpdate.proto\032\021Remov"
  "ePlane.proto\032\025RemoveAllPlanes.proto\032\026Net"
  "workConnected.proto\032\031NetworkDisconnected"
  ".proto\032\024AirplaneConfig.proto\032\027NearbyCont"
  "rollers.proto\032\034ClearNearbyControllers.pr"
  "oto\032\034PrivateMessageReceived.proto\032\030Priva"
  "teMessageSent.proto\032\030SetTransponderCode."
  "proto\032\030FastPositionUpdate.proto\032\025PlaneAd"
  "dedToSim.proto\"\270\010\n\007Wrapper\022-\n\ttimestamp\030"
  "\001 \001(\0132\032.google.protobuf.Timestamp\0221\n\017xpl"
  "ane_datarefs\030\002 \001(\0132\026.xpilot.XplaneDatare"
  "fsH\000\022)\n\013plugin_hash\030\003 \001(\0132\022.xpilot.Plugi"
  "nHashH\000\022/\n\016plugin_version\030\004 \001(\0132\025.xpilot"
  ".PluginVersionH\000\022+\n\014csl_validate\030\005 \001(\0132\023"
  ".xpilot.CslValidateH\000\022%\n\tadd_plane\030\006 \001(\013"
  "2\020.xpilot.AddPlaneH\000\022+\n\014change_model\030\007 \001"
  "(\0132\023.xpilot.ChangeModelH\000\0221\n\017position_up"
  "date\030\010 \001(\0132\026.xpilot.PositionUpdateH\000\022:\n\024"
  "fast_position_update\030\t \001(\0132\032.xpilot.Fast"
  "PositionUpdateH\000\022+\n\014remove_plane\030\n \001(\0132\023"
  ".xpilot.RemovePlaneH\000\0224\n\021remove_all_plan"
  "es\030\013 \001(\0132\027.xpilot.RemoveAllPlanesH\000\0225\n\021n"
  "etwork_connected\030\014 \001(\0132\030.xpilot.NetworkC"
  "onnectedH\000\022;\n\024network_disconnected\030\r \001(\013"
  "2\033.xpilot.NetworkDisconnectedH\000\0221\n\017airpl"
  "ane_config\030\016 \001(\0132\026.xpilot.AirplaneConfig"
  "H\000\0227\n\022nearby_controllers\030\017 \001(\0132\031.xpilot."
  "NearbyControllersH\000\022B\n\030clear_nearby_cont"
  "rollers\030\020 \001(\0132\036.xpilot.ClearNearbyContro"
  "llersH\000\022B\n\030private_message_received\030\021 \001("
  "\0132\036.xpilot.PrivateMessageReceivedH\000\022:\n\024p"
  "rivate_message_sent\030\022 \001(\0132\032.xpilot.Priva"
  "teMessageSentH\000\022:\n\024set_transponder_code\030"
  "\023 \001(\0132\032.xpilot.SetTransponderCodeH\000\0225\n\022p"
  "lane_added_to_sim\030\024 \001(\0132\027.xpilot.PlaneAd"
  "dedToSimH\000B\005\n\003msgB\031\252\002\026Vatsim.Xpilot.Prot"
  "obufb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Wrapper_2eproto_deps[20] = {
  &::descriptor_table_AddPlane_2eproto,
  &::descriptor_table_AirplaneConfig_2eproto,
  &::descriptor_table_CSLValidate_2eproto,
  &::descriptor_table_ChangeModel_2eproto,
  &::descriptor_table_ClearNearbyControllers_2eproto,
  &::descriptor_table_FastPositionUpdate_2eproto,
  &::descriptor_table_NearbyControllers_2eproto,
  &::descriptor_table_NetworkConnected_2eproto,
  &::descriptor_table_NetworkDisconnected_2eproto,
  &::descriptor_table_PlaneAddedToSim_2eproto,
  &::descriptor_table_PluginHash_2eproto,
  &::descriptor_table_PluginVersion_2eproto,
  &::descriptor_table_PositionUpdate_2eproto,
  &::descriptor_table_PrivateMessageReceived_2eproto,
  &::descriptor_table_PrivateMessageSent_2eproto,
  &::descriptor_table_RemoveAllPlanes_2eproto,
  &::descriptor_table_RemovePlane_2eproto,
  &::descriptor_table_SetTransponderCode_2eproto,
  &::descriptor_table_XplaneDatarefs_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Wrapper_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Wrapper_2eproto = {
  false, false, 1612, descriptor_table_protodef_Wrapper_2eproto, "Wrapper.proto", 
  &descriptor_table_Wrapper_2eproto_once, descriptor_table_Wrapper_2eproto_deps, 20, 1,
  schemas, file_default_instances, TableStruct_Wrapper_2eproto::offsets,
  file_level_metadata_Wrapper_2eproto, file_level_enum_descriptors_Wrapper_2eproto, file_level_service_descriptors_Wrapper_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_Wrapper_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Wrapper_2eproto);
  return descriptor_table_Wrapper_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Wrapper_2eproto(&descriptor_table_Wrapper_2eproto);
namespace xpilot {

// ===================================================================

class Wrapper::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp(const Wrapper* msg);
  static const ::xpilot::XplaneDatarefs& xplane_datarefs(const Wrapper* msg);
  static const ::xpilot::PluginHash& plugin_hash(const Wrapper* msg);
  static const ::xpilot::PluginVersion& plugin_version(const Wrapper* msg);
  static const ::xpilot::CslValidate& csl_validate(const Wrapper* msg);
  static const ::xpilot::AddPlane& add_plane(const Wrapper* msg);
  static const ::xpilot::ChangeModel& change_model(const Wrapper* msg);
  static const ::xpilot::PositionUpdate& position_update(const Wrapper* msg);
  static const ::xpilot::FastPositionUpdate& fast_position_update(const Wrapper* msg);
  static const ::xpilot::RemovePlane& remove_plane(const Wrapper* msg);
  static const ::xpilot::RemoveAllPlanes& remove_all_planes(const Wrapper* msg);
  static const ::xpilot::NetworkConnected& network_connected(const Wrapper* msg);
  static const ::xpilot::NetworkDisconnected& network_disconnected(const Wrapper* msg);
  static const ::xpilot::AirplaneConfig& airplane_config(const Wrapper* msg);
  static const ::xpilot::NearbyControllers& nearby_controllers(const Wrapper* msg);
  static const ::xpilot::ClearNearbyControllers& clear_nearby_controllers(const Wrapper* msg);
  static const ::xpilot::PrivateMessageReceived& private_message_received(const Wrapper* msg);
  static const ::xpilot::PrivateMessageSent& private_message_sent(const Wrapper* msg);
  static const ::xpilot::SetTransponderCode& set_transponder_code(const Wrapper* msg);
  static const ::xpilot::PlaneAddedToSim& plane_added_to_sim(const Wrapper* msg);
};

const PROTOBUF_NAMESPACE_ID::Timestamp&
Wrapper::_Internal::timestamp(const Wrapper* msg) {
  return *msg->timestamp_;
}
const ::xpilot::XplaneDatarefs&
Wrapper::_Internal::xplane_datarefs(const Wrapper* msg) {
  return *msg->msg_.xplane_datarefs_;
}
const ::xpilot::PluginHash&
Wrapper::_Internal::plugin_hash(const Wrapper* msg) {
  return *msg->msg_.plugin_hash_;
}
const ::xpilot::PluginVersion&
Wrapper::_Internal::plugin_version(const Wrapper* msg) {
  return *msg->msg_.plugin_version_;
}
const ::xpilot::CslValidate&
Wrapper::_Internal::csl_validate(const Wrapper* msg) {
  return *msg->msg_.csl_validate_;
}
const ::xpilot::AddPlane&
Wrapper::_Internal::add_plane(const Wrapper* msg) {
  return *msg->msg_.add_plane_;
}
const ::xpilot::ChangeModel&
Wrapper::_Internal::change_model(const Wrapper* msg) {
  return *msg->msg_.change_model_;
}
const ::xpilot::PositionUpdate&
Wrapper::_Internal::position_update(const Wrapper* msg) {
  return *msg->msg_.position_update_;
}
const ::xpilot::FastPositionUpdate&
Wrapper::_Internal::fast_position_update(const Wrapper* msg) {
  return *msg->msg_.fast_position_update_;
}
const ::xpilot::RemovePlane&
Wrapper::_Internal::remove_plane(const Wrapper* msg) {
  return *msg->msg_.remove_plane_;
}
const ::xpilot::RemoveAllPlanes&
Wrapper::_Internal::remove_all_planes(const Wrapper* msg) {
  return *msg->msg_.remove_all_planes_;
}
const ::xpilot::NetworkConnected&
Wrapper::_Internal::network_connected(const Wrapper* msg) {
  return *msg->msg_.network_connected_;
}
const ::xpilot::NetworkDisconnected&
Wrapper::_Internal::network_disconnected(const Wrapper* msg) {
  return *msg->msg_.network_disconnected_;
}
const ::xpilot::AirplaneConfig&
Wrapper::_Internal::airplane_config(const Wrapper* msg) {
  return *msg->msg_.airplane_config_;
}
const ::xpilot::NearbyControllers&
Wrapper::_Internal::nearby_controllers(const Wrapper* msg) {
  return *msg->msg_.nearby_controllers_;
}
const ::xpilot::ClearNearbyControllers&
Wrapper::_Internal::clear_nearby_controllers(const Wrapper* msg) {
  return *msg->msg_.clear_nearby_controllers_;
}
const ::xpilot::PrivateMessageReceived&
Wrapper::_Internal::private_message_received(const Wrapper* msg) {
  return *msg->msg_.private_message_received_;
}
const ::xpilot::PrivateMessageSent&
Wrapper::_Internal::private_message_sent(const Wrapper* msg) {
  return *msg->msg_.private_message_sent_;
}
const ::xpilot::SetTransponderCode&
Wrapper::_Internal::set_transponder_code(const Wrapper* msg) {
  return *msg->msg_.set_transponder_code_;
}
const ::xpilot::PlaneAddedToSim&
Wrapper::_Internal::plane_added_to_sim(const Wrapper* msg) {
  return *msg->msg_.plane_added_to_sim_;
}
void Wrapper::clear_timestamp() {
  if (GetArena() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
}
void Wrapper::set_allocated_xplane_datarefs(::xpilot::XplaneDatarefs* xplane_datarefs) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (xplane_datarefs) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(xplane_datarefs)->GetArena();
    if (message_arena != submessage_arena) {
      xplane_datarefs = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, xplane_datarefs, submessage_arena);
    }
    set_has_xplane_datarefs();
    msg_.xplane_datarefs_ = xplane_datarefs;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.xplane_datarefs)
}
void Wrapper::clear_xplane_datarefs() {
  if (_internal_has_xplane_datarefs()) {
    if (GetArena() == nullptr) {
      delete msg_.xplane_datarefs_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_plugin_hash(::xpilot::PluginHash* plugin_hash) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (plugin_hash) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(plugin_hash)->GetArena();
    if (message_arena != submessage_arena) {
      plugin_hash = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, plugin_hash, submessage_arena);
    }
    set_has_plugin_hash();
    msg_.plugin_hash_ = plugin_hash;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.plugin_hash)
}
void Wrapper::clear_plugin_hash() {
  if (_internal_has_plugin_hash()) {
    if (GetArena() == nullptr) {
      delete msg_.plugin_hash_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_plugin_version(::xpilot::PluginVersion* plugin_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (plugin_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(plugin_version)->GetArena();
    if (message_arena != submessage_arena) {
      plugin_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, plugin_version, submessage_arena);
    }
    set_has_plugin_version();
    msg_.plugin_version_ = plugin_version;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.plugin_version)
}
void Wrapper::clear_plugin_version() {
  if (_internal_has_plugin_version()) {
    if (GetArena() == nullptr) {
      delete msg_.plugin_version_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_csl_validate(::xpilot::CslValidate* csl_validate) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (csl_validate) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(csl_validate)->GetArena();
    if (message_arena != submessage_arena) {
      csl_validate = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, csl_validate, submessage_arena);
    }
    set_has_csl_validate();
    msg_.csl_validate_ = csl_validate;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.csl_validate)
}
void Wrapper::clear_csl_validate() {
  if (_internal_has_csl_validate()) {
    if (GetArena() == nullptr) {
      delete msg_.csl_validate_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_add_plane(::xpilot::AddPlane* add_plane) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (add_plane) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(add_plane)->GetArena();
    if (message_arena != submessage_arena) {
      add_plane = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, add_plane, submessage_arena);
    }
    set_has_add_plane();
    msg_.add_plane_ = add_plane;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.add_plane)
}
void Wrapper::clear_add_plane() {
  if (_internal_has_add_plane()) {
    if (GetArena() == nullptr) {
      delete msg_.add_plane_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_change_model(::xpilot::ChangeModel* change_model) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (change_model) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(change_model)->GetArena();
    if (message_arena != submessage_arena) {
      change_model = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, change_model, submessage_arena);
    }
    set_has_change_model();
    msg_.change_model_ = change_model;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.change_model)
}
void Wrapper::clear_change_model() {
  if (_internal_has_change_model()) {
    if (GetArena() == nullptr) {
      delete msg_.change_model_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_position_update(::xpilot::PositionUpdate* position_update) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (position_update) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_update)->GetArena();
    if (message_arena != submessage_arena) {
      position_update = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position_update, submessage_arena);
    }
    set_has_position_update();
    msg_.position_update_ = position_update;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.position_update)
}
void Wrapper::clear_position_update() {
  if (_internal_has_position_update()) {
    if (GetArena() == nullptr) {
      delete msg_.position_update_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_fast_position_update(::xpilot::FastPositionUpdate* fast_position_update) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (fast_position_update) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(fast_position_update)->GetArena();
    if (message_arena != submessage_arena) {
      fast_position_update = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, fast_position_update, submessage_arena);
    }
    set_has_fast_position_update();
    msg_.fast_position_update_ = fast_position_update;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.fast_position_update)
}
void Wrapper::clear_fast_position_update() {
  if (_internal_has_fast_position_update()) {
    if (GetArena() == nullptr) {
      delete msg_.fast_position_update_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_remove_plane(::xpilot::RemovePlane* remove_plane) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (remove_plane) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(remove_plane)->GetArena();
    if (message_arena != submessage_arena) {
      remove_plane = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, remove_plane, submessage_arena);
    }
    set_has_remove_plane();
    msg_.remove_plane_ = remove_plane;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.remove_plane)
}
void Wrapper::clear_remove_plane() {
  if (_internal_has_remove_plane()) {
    if (GetArena() == nullptr) {
      delete msg_.remove_plane_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_remove_all_planes(::xpilot::RemoveAllPlanes* remove_all_planes) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (remove_all_planes) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(remove_all_planes)->GetArena();
    if (message_arena != submessage_arena) {
      remove_all_planes = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, remove_all_planes, submessage_arena);
    }
    set_has_remove_all_planes();
    msg_.remove_all_planes_ = remove_all_planes;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.remove_all_planes)
}
void Wrapper::clear_remove_all_planes() {
  if (_internal_has_remove_all_planes()) {
    if (GetArena() == nullptr) {
      delete msg_.remove_all_planes_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_network_connected(::xpilot::NetworkConnected* network_connected) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (network_connected) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(network_connected)->GetArena();
    if (message_arena != submessage_arena) {
      network_connected = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, network_connected, submessage_arena);
    }
    set_has_network_connected();
    msg_.network_connected_ = network_connected;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.network_connected)
}
void Wrapper::clear_network_connected() {
  if (_internal_has_network_connected()) {
    if (GetArena() == nullptr) {
      delete msg_.network_connected_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_network_disconnected(::xpilot::NetworkDisconnected* network_disconnected) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (network_disconnected) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(network_disconnected)->GetArena();
    if (message_arena != submessage_arena) {
      network_disconnected = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, network_disconnected, submessage_arena);
    }
    set_has_network_disconnected();
    msg_.network_disconnected_ = network_disconnected;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.network_disconnected)
}
void Wrapper::clear_network_disconnected() {
  if (_internal_has_network_disconnected()) {
    if (GetArena() == nullptr) {
      delete msg_.network_disconnected_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_airplane_config(::xpilot::AirplaneConfig* airplane_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (airplane_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(airplane_config)->GetArena();
    if (message_arena != submessage_arena) {
      airplane_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, airplane_config, submessage_arena);
    }
    set_has_airplane_config();
    msg_.airplane_config_ = airplane_config;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.airplane_config)
}
void Wrapper::clear_airplane_config() {
  if (_internal_has_airplane_config()) {
    if (GetArena() == nullptr) {
      delete msg_.airplane_config_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_nearby_controllers(::xpilot::NearbyControllers* nearby_controllers) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (nearby_controllers) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(nearby_controllers)->GetArena();
    if (message_arena != submessage_arena) {
      nearby_controllers = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, nearby_controllers, submessage_arena);
    }
    set_has_nearby_controllers();
    msg_.nearby_controllers_ = nearby_controllers;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.nearby_controllers)
}
void Wrapper::clear_nearby_controllers() {
  if (_internal_has_nearby_controllers()) {
    if (GetArena() == nullptr) {
      delete msg_.nearby_controllers_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_clear_nearby_controllers(::xpilot::ClearNearbyControllers* clear_nearby_controllers) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (clear_nearby_controllers) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(clear_nearby_controllers)->GetArena();
    if (message_arena != submessage_arena) {
      clear_nearby_controllers = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, clear_nearby_controllers, submessage_arena);
    }
    set_has_clear_nearby_controllers();
    msg_.clear_nearby_controllers_ = clear_nearby_controllers;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.clear_nearby_controllers)
}
void Wrapper::clear_clear_nearby_controllers() {
  if (_internal_has_clear_nearby_controllers()) {
    if (GetArena() == nullptr) {
      delete msg_.clear_nearby_controllers_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_private_message_received(::xpilot::PrivateMessageReceived* private_message_received) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (private_message_received) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(private_message_received)->GetArena();
    if (message_arena != submessage_arena) {
      private_message_received = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, private_message_received, submessage_arena);
    }
    set_has_private_message_received();
    msg_.private_message_received_ = private_message_received;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.private_message_received)
}
void Wrapper::clear_private_message_received() {
  if (_internal_has_private_message_received()) {
    if (GetArena() == nullptr) {
      delete msg_.private_message_received_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_private_message_sent(::xpilot::PrivateMessageSent* private_message_sent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (private_message_sent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(private_message_sent)->GetArena();
    if (message_arena != submessage_arena) {
      private_message_sent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, private_message_sent, submessage_arena);
    }
    set_has_private_message_sent();
    msg_.private_message_sent_ = private_message_sent;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.private_message_sent)
}
void Wrapper::clear_private_message_sent() {
  if (_internal_has_private_message_sent()) {
    if (GetArena() == nullptr) {
      delete msg_.private_message_sent_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_set_transponder_code(::xpilot::SetTransponderCode* set_transponder_code) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (set_transponder_code) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(set_transponder_code)->GetArena();
    if (message_arena != submessage_arena) {
      set_transponder_code = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, set_transponder_code, submessage_arena);
    }
    set_has_set_transponder_code();
    msg_.set_transponder_code_ = set_transponder_code;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.set_transponder_code)
}
void Wrapper::clear_set_transponder_code() {
  if (_internal_has_set_transponder_code()) {
    if (GetArena() == nullptr) {
      delete msg_.set_transponder_code_;
    }
    clear_has_msg();
  }
}
void Wrapper::set_allocated_plane_added_to_sim(::xpilot::PlaneAddedToSim* plane_added_to_sim) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_msg();
  if (plane_added_to_sim) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(plane_added_to_sim)->GetArena();
    if (message_arena != submessage_arena) {
      plane_added_to_sim = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, plane_added_to_sim, submessage_arena);
    }
    set_has_plane_added_to_sim();
    msg_.plane_added_to_sim_ = plane_added_to_sim;
  }
  // @@protoc_insertion_point(field_set_allocated:xpilot.Wrapper.plane_added_to_sim)
}
void Wrapper::clear_plane_added_to_sim() {
  if (_internal_has_plane_added_to_sim()) {
    if (GetArena() == nullptr) {
      delete msg_.plane_added_to_sim_;
    }
    clear_has_msg();
  }
}
Wrapper::Wrapper(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:xpilot.Wrapper)
}
Wrapper::Wrapper(const Wrapper& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_timestamp()) {
    timestamp_ = new PROTOBUF_NAMESPACE_ID::Timestamp(*from.timestamp_);
  } else {
    timestamp_ = nullptr;
  }
  clear_has_msg();
  switch (from.msg_case()) {
    case kXplaneDatarefs: {
      _internal_mutable_xplane_datarefs()->::xpilot::XplaneDatarefs::MergeFrom(from._internal_xplane_datarefs());
      break;
    }
    case kPluginHash: {
      _internal_mutable_plugin_hash()->::xpilot::PluginHash::MergeFrom(from._internal_plugin_hash());
      break;
    }
    case kPluginVersion: {
      _internal_mutable_plugin_version()->::xpilot::PluginVersion::MergeFrom(from._internal_plugin_version());
      break;
    }
    case kCslValidate: {
      _internal_mutable_csl_validate()->::xpilot::CslValidate::MergeFrom(from._internal_csl_validate());
      break;
    }
    case kAddPlane: {
      _internal_mutable_add_plane()->::xpilot::AddPlane::MergeFrom(from._internal_add_plane());
      break;
    }
    case kChangeModel: {
      _internal_mutable_change_model()->::xpilot::ChangeModel::MergeFrom(from._internal_change_model());
      break;
    }
    case kPositionUpdate: {
      _internal_mutable_position_update()->::xpilot::PositionUpdate::MergeFrom(from._internal_position_update());
      break;
    }
    case kFastPositionUpdate: {
      _internal_mutable_fast_position_update()->::xpilot::FastPositionUpdate::MergeFrom(from._internal_fast_position_update());
      break;
    }
    case kRemovePlane: {
      _internal_mutable_remove_plane()->::xpilot::RemovePlane::MergeFrom(from._internal_remove_plane());
      break;
    }
    case kRemoveAllPlanes: {
      _internal_mutable_remove_all_planes()->::xpilot::RemoveAllPlanes::MergeFrom(from._internal_remove_all_planes());
      break;
    }
    case kNetworkConnected: {
      _internal_mutable_network_connected()->::xpilot::NetworkConnected::MergeFrom(from._internal_network_connected());
      break;
    }
    case kNetworkDisconnected: {
      _internal_mutable_network_disconnected()->::xpilot::NetworkDisconnected::MergeFrom(from._internal_network_disconnected());
      break;
    }
    case kAirplaneConfig: {
      _internal_mutable_airplane_config()->::xpilot::AirplaneConfig::MergeFrom(from._internal_airplane_config());
      break;
    }
    case kNearbyControllers: {
      _internal_mutable_nearby_controllers()->::xpilot::NearbyControllers::MergeFrom(from._internal_nearby_controllers());
      break;
    }
    case kClearNearbyControllers: {
      _internal_mutable_clear_nearby_controllers()->::xpilot::ClearNearbyControllers::MergeFrom(from._internal_clear_nearby_controllers());
      break;
    }
    case kPrivateMessageReceived: {
      _internal_mutable_private_message_received()->::xpilot::PrivateMessageReceived::MergeFrom(from._internal_private_message_received());
      break;
    }
    case kPrivateMessageSent: {
      _internal_mutable_private_message_sent()->::xpilot::PrivateMessageSent::MergeFrom(from._internal_private_message_sent());
      break;
    }
    case kSetTransponderCode: {
      _internal_mutable_set_transponder_code()->::xpilot::SetTransponderCode::MergeFrom(from._internal_set_transponder_code());
      break;
    }
    case kPlaneAddedToSim: {
      _internal_mutable_plane_added_to_sim()->::xpilot::PlaneAddedToSim::MergeFrom(from._internal_plane_added_to_sim());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:xpilot.Wrapper)
}

void Wrapper::SharedCtor() {
timestamp_ = nullptr;
clear_has_msg();
}

Wrapper::~Wrapper() {
  // @@protoc_insertion_point(destructor:xpilot.Wrapper)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Wrapper::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete timestamp_;
  if (has_msg()) {
    clear_msg();
  }
}

void Wrapper::ArenaDtor(void* object) {
  Wrapper* _this = reinterpret_cast< Wrapper* >(object);
  (void)_this;
}
void Wrapper::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Wrapper::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Wrapper::clear_msg() {
// @@protoc_insertion_point(one_of_clear_start:xpilot.Wrapper)
  switch (msg_case()) {
    case kXplaneDatarefs: {
      if (GetArena() == nullptr) {
        delete msg_.xplane_datarefs_;
      }
      break;
    }
    case kPluginHash: {
      if (GetArena() == nullptr) {
        delete msg_.plugin_hash_;
      }
      break;
    }
    case kPluginVersion: {
      if (GetArena() == nullptr) {
        delete msg_.plugin_version_;
      }
      break;
    }
    case kCslValidate: {
      if (GetArena() == nullptr) {
        delete msg_.csl_validate_;
      }
      break;
    }
    case kAddPlane: {
      if (GetArena() == nullptr) {
        delete msg_.add_plane_;
      }
      break;
    }
    case kChangeModel: {
      if (GetArena() == nullptr) {
        delete msg_.change_model_;
      }
      break;
    }
    case kPositionUpdate: {
      if (GetArena() == nullptr) {
        delete msg_.position_update_;
      }
      break;
    }
    case kFastPositionUpdate: {
      if (GetArena() == nullptr) {
        delete msg_.fast_position_update_;
      }
      break;
    }
    case kRemovePlane: {
      if (GetArena() == nullptr) {
        delete msg_.remove_plane_;
      }
      break;
    }
    case kRemoveAllPlanes: {
      if (GetArena() == nullptr) {
        delete msg_.remove_all_planes_;
      }
      break;
    }
    case kNetworkConnected: {
      if (GetArena() == nullptr) {
        delete msg_.network_connected_;
      }
      break;
    }
    case kNetworkDisconnected: {
      if (GetArena() == nullptr) {
        delete msg_.network_disconnected_;
      }
      break;
    }
    case kAirplaneConfig: {
      if (GetArena() == nullptr) {
        delete msg_.airplane_config_;
      }
      break;
    }
    case kNearbyControllers: {
      if (GetArena() == nullptr) {
        delete msg_.nearby_controllers_;
      }
      break;
    }
    case kClearNearbyControllers: {
      if (GetArena() == nullptr) {
        delete msg_.clear_nearby_controllers_;
      }
      break;
    }
    case kPrivateMessageReceived: {
      if (GetArena() == nullptr) {
        delete msg_.private_message_received_;
      }
      break;
    }
    case kPrivateMessageSent: {
      if (GetArena() == nullptr) {
        delete msg_.private_message_sent_;
      }
      break;
    }
    case kSetTransponderCode: {
      if (GetArena() == nullptr) {
        delete msg_.set_transponder_code_;
      }
      break;
    }
    case kPlaneAddedToSim: {
      if (GetArena() == nullptr) {
        delete msg_.plane_added_to_sim_;
      }
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MSG_NOT_SET;
}


void Wrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:xpilot.Wrapper)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
  clear_msg();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Wrapper::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .google.protobuf.Timestamp timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.XplaneDatarefs xplane_datarefs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_xplane_datarefs(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.PluginHash plugin_hash = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_plugin_hash(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.PluginVersion plugin_version = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_plugin_version(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.CslValidate csl_validate = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_csl_validate(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.AddPlane add_plane = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_add_plane(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.ChangeModel change_model = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_change_model(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.PositionUpdate position_update = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_position_update(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.FastPositionUpdate fast_position_update = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_fast_position_update(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.RemovePlane remove_plane = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_remove_plane(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.RemoveAllPlanes remove_all_planes = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_remove_all_planes(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.NetworkConnected network_connected = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_network_connected(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.NetworkDisconnected network_disconnected = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_network_disconnected(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.AirplaneConfig airplane_config = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          ptr = ctx->ParseMessage(_internal_mutable_airplane_config(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.NearbyControllers nearby_controllers = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 122)) {
          ptr = ctx->ParseMessage(_internal_mutable_nearby_controllers(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.ClearNearbyControllers clear_nearby_controllers = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 130)) {
          ptr = ctx->ParseMessage(_internal_mutable_clear_nearby_controllers(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.PrivateMessageReceived private_message_received = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 138)) {
          ptr = ctx->ParseMessage(_internal_mutable_private_message_received(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.PrivateMessageSent private_message_sent = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 146)) {
          ptr = ctx->ParseMessage(_internal_mutable_private_message_sent(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.SetTransponderCode set_transponder_code = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 154)) {
          ptr = ctx->ParseMessage(_internal_mutable_set_transponder_code(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .xpilot.PlaneAddedToSim plane_added_to_sim = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr = ctx->ParseMessage(_internal_mutable_plane_added_to_sim(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Wrapper::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xpilot.Wrapper)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->has_timestamp()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::timestamp(this), target, stream);
  }

  // .xpilot.XplaneDatarefs xplane_datarefs = 2;
  if (_internal_has_xplane_datarefs()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::xplane_datarefs(this), target, stream);
  }

  // .xpilot.PluginHash plugin_hash = 3;
  if (_internal_has_plugin_hash()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::plugin_hash(this), target, stream);
  }

  // .xpilot.PluginVersion plugin_version = 4;
  if (_internal_has_plugin_version()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::plugin_version(this), target, stream);
  }

  // .xpilot.CslValidate csl_validate = 5;
  if (_internal_has_csl_validate()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::csl_validate(this), target, stream);
  }

  // .xpilot.AddPlane add_plane = 6;
  if (_internal_has_add_plane()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::add_plane(this), target, stream);
  }

  // .xpilot.ChangeModel change_model = 7;
  if (_internal_has_change_model()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::change_model(this), target, stream);
  }

  // .xpilot.PositionUpdate position_update = 8;
  if (_internal_has_position_update()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::position_update(this), target, stream);
  }

  // .xpilot.FastPositionUpdate fast_position_update = 9;
  if (_internal_has_fast_position_update()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        9, _Internal::fast_position_update(this), target, stream);
  }

  // .xpilot.RemovePlane remove_plane = 10;
  if (_internal_has_remove_plane()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        10, _Internal::remove_plane(this), target, stream);
  }

  // .xpilot.RemoveAllPlanes remove_all_planes = 11;
  if (_internal_has_remove_all_planes()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        11, _Internal::remove_all_planes(this), target, stream);
  }

  // .xpilot.NetworkConnected network_connected = 12;
  if (_internal_has_network_connected()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        12, _Internal::network_connected(this), target, stream);
  }

  // .xpilot.NetworkDisconnected network_disconnected = 13;
  if (_internal_has_network_disconnected()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        13, _Internal::network_disconnected(this), target, stream);
  }

  // .xpilot.AirplaneConfig airplane_config = 14;
  if (_internal_has_airplane_config()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        14, _Internal::airplane_config(this), target, stream);
  }

  // .xpilot.NearbyControllers nearby_controllers = 15;
  if (_internal_has_nearby_controllers()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        15, _Internal::nearby_controllers(this), target, stream);
  }

  // .xpilot.ClearNearbyControllers clear_nearby_controllers = 16;
  if (_internal_has_clear_nearby_controllers()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        16, _Internal::clear_nearby_controllers(this), target, stream);
  }

  // .xpilot.PrivateMessageReceived private_message_received = 17;
  if (_internal_has_private_message_received()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        17, _Internal::private_message_received(this), target, stream);
  }

  // .xpilot.PrivateMessageSent private_message_sent = 18;
  if (_internal_has_private_message_sent()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        18, _Internal::private_message_sent(this), target, stream);
  }

  // .xpilot.SetTransponderCode set_transponder_code = 19;
  if (_internal_has_set_transponder_code()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        19, _Internal::set_transponder_code(this), target, stream);
  }

  // .xpilot.PlaneAddedToSim plane_added_to_sim = 20;
  if (_internal_has_plane_added_to_sim()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        20, _Internal::plane_added_to_sim(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xpilot.Wrapper)
  return target;
}

size_t Wrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xpilot.Wrapper)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->has_timestamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *timestamp_);
  }

  switch (msg_case()) {
    // .xpilot.XplaneDatarefs xplane_datarefs = 2;
    case kXplaneDatarefs: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.xplane_datarefs_);
      break;
    }
    // .xpilot.PluginHash plugin_hash = 3;
    case kPluginHash: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.plugin_hash_);
      break;
    }
    // .xpilot.PluginVersion plugin_version = 4;
    case kPluginVersion: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.plugin_version_);
      break;
    }
    // .xpilot.CslValidate csl_validate = 5;
    case kCslValidate: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.csl_validate_);
      break;
    }
    // .xpilot.AddPlane add_plane = 6;
    case kAddPlane: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.add_plane_);
      break;
    }
    // .xpilot.ChangeModel change_model = 7;
    case kChangeModel: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.change_model_);
      break;
    }
    // .xpilot.PositionUpdate position_update = 8;
    case kPositionUpdate: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.position_update_);
      break;
    }
    // .xpilot.FastPositionUpdate fast_position_update = 9;
    case kFastPositionUpdate: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.fast_position_update_);
      break;
    }
    // .xpilot.RemovePlane remove_plane = 10;
    case kRemovePlane: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.remove_plane_);
      break;
    }
    // .xpilot.RemoveAllPlanes remove_all_planes = 11;
    case kRemoveAllPlanes: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.remove_all_planes_);
      break;
    }
    // .xpilot.NetworkConnected network_connected = 12;
    case kNetworkConnected: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.network_connected_);
      break;
    }
    // .xpilot.NetworkDisconnected network_disconnected = 13;
    case kNetworkDisconnected: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.network_disconnected_);
      break;
    }
    // .xpilot.AirplaneConfig airplane_config = 14;
    case kAirplaneConfig: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.airplane_config_);
      break;
    }
    // .xpilot.NearbyControllers nearby_controllers = 15;
    case kNearbyControllers: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.nearby_controllers_);
      break;
    }
    // .xpilot.ClearNearbyControllers clear_nearby_controllers = 16;
    case kClearNearbyControllers: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.clear_nearby_controllers_);
      break;
    }
    // .xpilot.PrivateMessageReceived private_message_received = 17;
    case kPrivateMessageReceived: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.private_message_received_);
      break;
    }
    // .xpilot.PrivateMessageSent private_message_sent = 18;
    case kPrivateMessageSent: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.private_message_sent_);
      break;
    }
    // .xpilot.SetTransponderCode set_transponder_code = 19;
    case kSetTransponderCode: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.set_transponder_code_);
      break;
    }
    // .xpilot.PlaneAddedToSim plane_added_to_sim = 20;
    case kPlaneAddedToSim: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *msg_.plane_added_to_sim_);
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Wrapper::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:xpilot.Wrapper)
  GOOGLE_DCHECK_NE(&from, this);
  const Wrapper* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Wrapper>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:xpilot.Wrapper)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:xpilot.Wrapper)
    MergeFrom(*source);
  }
}

void Wrapper::MergeFrom(const Wrapper& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:xpilot.Wrapper)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_timestamp()) {
    _internal_mutable_timestamp()->PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(from._internal_timestamp());
  }
  switch (from.msg_case()) {
    case kXplaneDatarefs: {
      _internal_mutable_xplane_datarefs()->::xpilot::XplaneDatarefs::MergeFrom(from._internal_xplane_datarefs());
      break;
    }
    case kPluginHash: {
      _internal_mutable_plugin_hash()->::xpilot::PluginHash::MergeFrom(from._internal_plugin_hash());
      break;
    }
    case kPluginVersion: {
      _internal_mutable_plugin_version()->::xpilot::PluginVersion::MergeFrom(from._internal_plugin_version());
      break;
    }
    case kCslValidate: {
      _internal_mutable_csl_validate()->::xpilot::CslValidate::MergeFrom(from._internal_csl_validate());
      break;
    }
    case kAddPlane: {
      _internal_mutable_add_plane()->::xpilot::AddPlane::MergeFrom(from._internal_add_plane());
      break;
    }
    case kChangeModel: {
      _internal_mutable_change_model()->::xpilot::ChangeModel::MergeFrom(from._internal_change_model());
      break;
    }
    case kPositionUpdate: {
      _internal_mutable_position_update()->::xpilot::PositionUpdate::MergeFrom(from._internal_position_update());
      break;
    }
    case kFastPositionUpdate: {
      _internal_mutable_fast_position_update()->::xpilot::FastPositionUpdate::MergeFrom(from._internal_fast_position_update());
      break;
    }
    case kRemovePlane: {
      _internal_mutable_remove_plane()->::xpilot::RemovePlane::MergeFrom(from._internal_remove_plane());
      break;
    }
    case kRemoveAllPlanes: {
      _internal_mutable_remove_all_planes()->::xpilot::RemoveAllPlanes::MergeFrom(from._internal_remove_all_planes());
      break;
    }
    case kNetworkConnected: {
      _internal_mutable_network_connected()->::xpilot::NetworkConnected::MergeFrom(from._internal_network_connected());
      break;
    }
    case kNetworkDisconnected: {
      _internal_mutable_network_disconnected()->::xpilot::NetworkDisconnected::MergeFrom(from._internal_network_disconnected());
      break;
    }
    case kAirplaneConfig: {
      _internal_mutable_airplane_config()->::xpilot::AirplaneConfig::MergeFrom(from._internal_airplane_config());
      break;
    }
    case kNearbyControllers: {
      _internal_mutable_nearby_controllers()->::xpilot::NearbyControllers::MergeFrom(from._internal_nearby_controllers());
      break;
    }
    case kClearNearbyControllers: {
      _internal_mutable_clear_nearby_controllers()->::xpilot::ClearNearbyControllers::MergeFrom(from._internal_clear_nearby_controllers());
      break;
    }
    case kPrivateMessageReceived: {
      _internal_mutable_private_message_received()->::xpilot::PrivateMessageReceived::MergeFrom(from._internal_private_message_received());
      break;
    }
    case kPrivateMessageSent: {
      _internal_mutable_private_message_sent()->::xpilot::PrivateMessageSent::MergeFrom(from._internal_private_message_sent());
      break;
    }
    case kSetTransponderCode: {
      _internal_mutable_set_transponder_code()->::xpilot::SetTransponderCode::MergeFrom(from._internal_set_transponder_code());
      break;
    }
    case kPlaneAddedToSim: {
      _internal_mutable_plane_added_to_sim()->::xpilot::PlaneAddedToSim::MergeFrom(from._internal_plane_added_to_sim());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
}

void Wrapper::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:xpilot.Wrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Wrapper::CopyFrom(const Wrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xpilot.Wrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Wrapper::IsInitialized() const {
  return true;
}

void Wrapper::InternalSwap(Wrapper* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(timestamp_, other->timestamp_);
  swap(msg_, other->msg_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Wrapper::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace xpilot
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::xpilot::Wrapper* Arena::CreateMaybeMessage< ::xpilot::Wrapper >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xpilot::Wrapper >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
