name: macOS

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Install conan && conan package tools
        run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install conan_package_tools

      - uses: actions/checkout@v1
        with:
          submodules: "recursive"

      - name: Create build environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Initialize Conan
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: conan install $GITHUB_WORKSPACE --build missing

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config Release