name: macOS

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v1
        with:
          submodules: "recursive"

      - name: Install conan && conan package tools
        run: |
          python3 -m pip install --upgrade pip
          pip3 install conan
          pip3 install conan_package_tools

      - name: Create build environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Install conan packages
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: conan install $GITHUB_WORKSPACE --build missing

      - name: CMake
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: make