name: Build xPilot Plugin

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      matrix:
        kind: ["linux", "windows", "macos"]
        include:
          - kind: linux
            os: ubuntu-latest
          - kind: windows
            os: windows-latest
          - kind: macos
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    
      - name: Checkout
        uses: actions/checkout@v1
          with:
            submodules: "recursive"

      - name: Create build environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Initialize Conan
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: conan install $GITHUB_WORKSPACE --build missing

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config Release